### ISSUE TITLE
No provider for language TypeScript/VueJS/etc

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/sourceplusplus#719]
```
java.lang.IllegalArgumentException: No provider for language TypeScript
	at spp.jetbrains.marker.impl.SourceGuideProvider.getProvider(SourceGuideProvider.kt:49)
	at spp.jetbrains.marker.impl.SourceGuideProvider.determineGuideMarks$lambda-6(SourceGuideProvider.kt:54)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:58)
	at spp.jetbrains.marker.impl.SourceGuideProvider.determineGuideMarks(SourceGuideProvider.kt:53)
	at spp.jetbrains.marker.SourceMarker$getSourceFileMarker$2.invokeSuspend(SourceMarker.kt:108)
	at spp.jetbrains.marker.SourceMarker$getSourceFileMarker$2.invoke(SourceMarker.kt)
	at spp.jetbrains.marker.SourceMarker$getSourceFileMarker$2.invoke(SourceMarker.kt)
	at spp.jetbrains.ScopeExtensions$safeGlobalLaunch$1$1.invokeSuspend(ScopeExtensions.kt:61)
	at spp.jetbrains.ScopeExtensions$safeGlobalLaunch$1$1.invoke(ScopeExtensions.kt)
	at spp.jetbrains.ScopeExtensions$safeGlobalLaunch$1$1.invoke(ScopeExtensions.kt)
	at spp.jetbrains.ScopeExtensions.safeExecute(ScopeExtensions.kt:52)
	at spp.jetbrains.ScopeExtensions$safeGlobalLaunch$1.invokeSuspend(ScopeExtensions.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by BFergerson** [comment]
Should simply check if providers are availalble. Ignore if they're not
